language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kuldeepaujla/react-docker -f Dockerfile.dev .

scripts:
  - docker run -e CI=true kuldeepaujla/react-docker npm run test

after_success:
  - docker build -t kuldeepaujla/react-docker .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER"
  - docker push kuldeepaujla/react-docker